----case when then 设置成功、失败、代签、正在盖章等状态   918
SELECT   DOC_UNIQUE, DOC_NAME, SUBSTRING(DOC_DOCUMENTID, 10, 45) AS DOC_REAL_NAME, DOC_TYPE, DOC_STATUS, CREATE_TIME, ErrorMsg, 
CASE WHEN DOC_STATUS = '2' THEN '成功' 
WHEN DOC_STATUS = '3' THEN '失败' 
WHEN DOC_STATUS = '1' THEN '代签' 
WHEN DOC_STATUS = '6' THEN '正在盖章'
END AS STATUS
FROM  SIGN_DOCNUMET WHERE  (DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45)))
 --AND CREATE_TIME>='2016.09.01'
-- and doc_status='2'
ORDER BY DOC_UNIQUE DESC



---文件签名次数
SELECT   MAX(DOC_UNIQUE) AS DOC_UNIQUE,count(SUBSTRING(DOC_DOCUMENTID, 10, 45)) as TIMES 
FROM  SIGN_DOCNUMET WHERE  (DOC_DOCUMENTID LIKE '%@%')
GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45)
order by DOC_UNIQUE desc


---文件签名次数DOC_UNIQUE
SELECT   MAX(DOC_UNIQUE) AS DOC_UNIQUE
FROM  SIGN_DOCNUMET WHERE  (DOC_DOCUMENTID LIKE '%@%')
GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45)


---文件TEMPLATE_UNIQUE
select TEMPLATE_UNIQUE from REL_DOC_STEMP
where DOC_UNIQUE in
(SELECT   MAX(DOC_UNIQUE) AS DOC_UNIQUE
FROM  SIGN_DOCNUMET WHERE  (DOC_DOCUMENTID LIKE '%@%')
GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))





---301
SELECT SIGN_DOCNUMET.DOC_UNIQUE,
SIGN_TEMPLATE_CAD.SIGN_KEY,SIGN_TEMPLATE_CAD.SIGN_NAME
FROM SIGN_DOCNUMET,REL_DOC_STEMP,SIGN_TEMPLATE_CAD
WHERE SIGN_DOCNUMET.DOC_UNIQUE = REL_DOC_STEMP.DOC_UNIQUE
AND REL_DOC_STEMP.TEMPLATE_UNIQUE = SIGN_TEMPLATE_CAD.TEMPLATE_UNIQUE
AND SIGN_DOCNUMET.DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))
 AND MARK_NAME='设计'
ORDER BY DOC_UNIQUE DESC



--533
SELECT SIGN_DOCNUMET.DOC_UNIQUE,
SIGN_TEMPLATE_WPS.SIGN_KEY,SIGN_TEMPLATE_WPS.SIGN_NAME
FROM SIGN_DOCNUMET,REL_DOC_STEMP,SIGN_TEMPLATE_WPS
WHERE SIGN_DOCNUMET.DOC_UNIQUE = REL_DOC_STEMP.DOC_UNIQUE
AND REL_DOC_STEMP.TEMPLATE_UNIQUE = SIGN_TEMPLATE_WPS.TEMPLATE_UNIQUE
AND SIGN_DOCNUMET.DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))
 AND MARK_NAME='设计'
ORDER BY DOC_UNIQUE DESC




---834 简单版
SELECT SIGN_DOCNUMET.DOC_UNIQUE,
SIGN_TEMPLATE_CAD.SIGN_KEY,SIGN_TEMPLATE_CAD.SIGN_NAME
FROM SIGN_DOCNUMET,REL_DOC_STEMP,SIGN_TEMPLATE_CAD
WHERE SIGN_DOCNUMET.DOC_UNIQUE = REL_DOC_STEMP.DOC_UNIQUE
AND REL_DOC_STEMP.TEMPLATE_UNIQUE = SIGN_TEMPLATE_CAD.TEMPLATE_UNIQUE
AND SIGN_DOCNUMET.DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))
 AND MARK_NAME='设计'
 union
 (SELECT SIGN_DOCNUMET.DOC_UNIQUE,
SIGN_TEMPLATE_WPS.SIGN_KEY,SIGN_TEMPLATE_WPS.SIGN_NAME
FROM SIGN_DOCNUMET,REL_DOC_STEMP,SIGN_TEMPLATE_WPS
WHERE SIGN_DOCNUMET.DOC_UNIQUE = REL_DOC_STEMP.DOC_UNIQUE
AND REL_DOC_STEMP.TEMPLATE_UNIQUE = SIGN_TEMPLATE_WPS.TEMPLATE_UNIQUE
AND SIGN_DOCNUMET.DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))
 AND MARK_NAME='设计')


---834 复杂版
SELECT SIGN_DOCNUMET.DOC_UNIQUE,SIGN_DOCNUMET.DOC_NAME, SUBSTRING(SIGN_DOCNUMET.DOC_DOCUMENTID, 10, 40) AS DOC_REAL_NAME,
 SIGN_DOCNUMET.DOC_TYPE, SIGN_DOCNUMET.DOC_STATUS, SIGN_DOCNUMET.CREATE_TIME, SIGN_DOCNUMET.ErrorMsg, 
 CASE WHEN SIGN_DOCNUMET.DOC_STATUS = '2' THEN '成功' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '3' THEN '失败' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '1' THEN '代签' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '6' THEN '正在盖章'
END AS STATUS,
SIGN_TEMPLATE_CAD.SIGN_NAME AS [USRNAME],SIGN_TEMPLATE_CAD.SIGN_KEY AS [USRCODE]
FROM SIGN_DOCNUMET,REL_DOC_STEMP,SIGN_TEMPLATE_CAD
WHERE SIGN_DOCNUMET.DOC_UNIQUE = REL_DOC_STEMP.DOC_UNIQUE
AND REL_DOC_STEMP.TEMPLATE_UNIQUE = SIGN_TEMPLATE_CAD.TEMPLATE_UNIQUE
AND SIGN_DOCNUMET.DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))
 AND MARK_NAME='设计'
UNION
(SELECT SIGN_DOCNUMET.DOC_UNIQUE,SIGN_DOCNUMET.DOC_NAME, SUBSTRING(SIGN_DOCNUMET.DOC_DOCUMENTID, 10, 40) AS DOC_REAL_NAME, 
SIGN_DOCNUMET.DOC_TYPE, SIGN_DOCNUMET.DOC_STATUS, SIGN_DOCNUMET.CREATE_TIME, SIGN_DOCNUMET.ErrorMsg,
 CASE WHEN SIGN_DOCNUMET.DOC_STATUS = '2' THEN '成功' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '3' THEN '失败' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '1' THEN '代签' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '6' THEN '正在盖章'
END AS STATUS,
SIGN_TEMPLATE_WPS.SIGN_NAME AS [USRNAME],SIGN_TEMPLATE_WPS.SIGN_KEY AS [USRCODE]
FROM SIGN_DOCNUMET,REL_DOC_STEMP,SIGN_TEMPLATE_WPS
WHERE SIGN_DOCNUMET.DOC_UNIQUE = REL_DOC_STEMP.DOC_UNIQUE
AND REL_DOC_STEMP.TEMPLATE_UNIQUE = SIGN_TEMPLATE_WPS.TEMPLATE_UNIQUE
AND SIGN_DOCNUMET.DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))
 AND MARK_NAME='设计'
) 
ORDER BY DOC_UNIQUE DESC



----插入到新表（SIGN_DOCNUMET_INSIG_INFO）
DELETE FROM dbo.SIGN_DOCNUMET_INSIG_INFO


 --插入,[DOC_UNIQUE],[DOC_NAME],[DOC_REAL_NAME],[DOC_TYPE],[DOC_STATUS],[CREATE_TIME],[ErrorMsg],[STATUS],[USRNAME],[USRCODE]
 INSERT INTO [dbo].[SIGN_DOCNUMET_INSIG_INFO]
([DOC_UNIQUE],[DOC_NAME],[DOC_REAL_NAME],[DOC_TYPE],[DOC_STATUS],[CREATE_TIME],[ErrorMsg],[STATUS],[USRNAME],[USRCODE])
(SELECT SIGN_DOCNUMET.DOC_UNIQUE,SIGN_DOCNUMET.DOC_NAME, SUBSTRING(SIGN_DOCNUMET.DOC_DOCUMENTID, 10, 45) AS DOC_REAL_NAME,
 SIGN_DOCNUMET.DOC_TYPE, SIGN_DOCNUMET.DOC_STATUS, SIGN_DOCNUMET.CREATE_TIME, SIGN_DOCNUMET.ErrorMsg, 
 CASE WHEN SIGN_DOCNUMET.DOC_STATUS = '2' THEN '成功' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '3' THEN '失败' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '1' THEN '代签' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '6' THEN '正在盖章'
END AS STATUS,
SIGN_TEMPLATE_CAD.SIGN_NAME,SIGN_TEMPLATE_CAD.SIGN_KEY
FROM SIGN_DOCNUMET,REL_DOC_STEMP,SIGN_TEMPLATE_CAD
WHERE SIGN_DOCNUMET.DOC_UNIQUE = REL_DOC_STEMP.DOC_UNIQUE
AND REL_DOC_STEMP.TEMPLATE_UNIQUE = SIGN_TEMPLATE_CAD.TEMPLATE_UNIQUE
AND SIGN_DOCNUMET.DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))
 AND MARK_NAME='设计'
UNION
(SELECT SIGN_DOCNUMET.DOC_UNIQUE,SIGN_DOCNUMET.DOC_NAME, SUBSTRING(SIGN_DOCNUMET.DOC_DOCUMENTID, 10, 40) AS DOC_REAL_NAME, 
SIGN_DOCNUMET.DOC_TYPE, SIGN_DOCNUMET.DOC_STATUS, SIGN_DOCNUMET.CREATE_TIME, SIGN_DOCNUMET.ErrorMsg,
 CASE WHEN SIGN_DOCNUMET.DOC_STATUS = '2' THEN '成功' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '3' THEN '失败' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '1' THEN '代签' 
WHEN SIGN_DOCNUMET.DOC_STATUS = '6' THEN '正在盖章'
END AS STATUS,
SIGN_TEMPLATE_WPS.SIGN_NAME,SIGN_TEMPLATE_WPS.SIGN_KEY
FROM SIGN_DOCNUMET,REL_DOC_STEMP,SIGN_TEMPLATE_WPS
WHERE SIGN_DOCNUMET.DOC_UNIQUE = REL_DOC_STEMP.DOC_UNIQUE
AND REL_DOC_STEMP.TEMPLATE_UNIQUE = SIGN_TEMPLATE_WPS.TEMPLATE_UNIQUE
AND SIGN_DOCNUMET.DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))
 AND MARK_NAME='设计'
))



----查找不存在的，插入   77+7=84
SELECT   DOC_UNIQUE, DOC_NAME, SUBSTRING(DOC_DOCUMENTID, 10, 45) AS DOC_REAL_NAME, DOC_TYPE, DOC_STATUS, CREATE_TIME, ErrorMsg, 
CASE WHEN DOC_STATUS = '2' THEN '成功' 
WHEN DOC_STATUS = '3' THEN '失败' 
WHEN DOC_STATUS = '1' THEN '代签' 
WHEN DOC_STATUS = '6' THEN '正在盖章'
END AS STATUS
FROM  SIGN_DOCNUMET WHERE  (DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))) and DOC_UNIQUE not in
 (select DOC_UNIQUE from SIGN_DOCNUMET_INSIG_INFO)


 --插入[DOC_UNIQUE],[DOC_NAME],[DOC_REAL_NAME],[DOC_TYPE],[DOC_STATUS],[CREATE_TIME],[ErrorMsg],[STATUS]字段
INSERT INTO [dbo].[SIGN_DOCNUMET_INSIG_INFO]
([DOC_UNIQUE],[DOC_NAME],[DOC_REAL_NAME],[DOC_TYPE],[DOC_STATUS],[CREATE_TIME],[ErrorMsg],[STATUS])
(SELECT   DOC_UNIQUE, DOC_NAME, SUBSTRING(DOC_DOCUMENTID, 10, 45) AS DOC_REAL_NAME, DOC_TYPE, DOC_STATUS, CREATE_TIME, ErrorMsg, 
CASE WHEN DOC_STATUS = '2' THEN '成功' 
WHEN DOC_STATUS = '3' THEN '失败' 
WHEN DOC_STATUS = '1' THEN '代签' 
WHEN DOC_STATUS = '6' THEN '正在盖章'
END AS STATUS
FROM  SIGN_DOCNUMET WHERE  (DOC_UNIQUE IN
(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1
 WHERE   (DOC_DOCUMENTID LIKE '%@%')
 GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))) and DOC_UNIQUE not in
 (select DOC_UNIQUE from SIGN_DOCNUMET_INSIG_INFO))




 ----


DELETE FROM dbo.SIGN_DOCNUMET_INSIG_INFO


INSERT INTO [dbo].[SIGN_DOCNUMET_INSIG_INFO]([DOC_UNIQUE],[DOC_NAME],[DOC_REAL_NAME],[DOC_TYPE],[DOC_STATUS],[CREATE_TIME],[ErrorMsg],[STATUS],[USRNAME],[USRCODE])(SELECT SIGN_DOCNUMET.DOC_UNIQUE,SIGN_DOCNUMET.DOC_NAME,SUBSTRING(SIGN_DOCNUMET.DOC_DOCUMENTID, 10, 40) AS DOC_REAL_NAME,SIGN_DOCNUMET.DOC_TYPE, SIGN_DOCNUMET.DOC_STATUS, SIGN_DOCNUMET.CREATE_TIME, SIGN_DOCNUMET.ErrorMsg, CASE WHEN SIGN_DOCNUMET.DOC_STATUS = '2' THEN '成功' WHEN SIGN_DOCNUMET.DOC_STATUS = '3' THEN '失败' WHEN SIGN_DOCNUMET.DOC_STATUS = '1' THEN '代签' WHEN SIGN_DOCNUMET.DOC_STATUS = '6' THEN '正在盖章'END AS STATUS,SIGN_TEMPLATE_CAD.SIGN_NAME AS [USRNAME],SIGN_TEMPLATE_CAD.SIGN_KEY AS [USRCODE]FROM SIGN_DOCNUMET,REL_DOC_STEMP,SIGN_TEMPLATE_CAD WHERE SIGN_DOCNUMET.DOC_UNIQUE = REL_DOC_STEMP.DOC_UNIQUE AND REL_DOC_STEMP.TEMPLATE_UNIQUE = SIGN_TEMPLATE_CAD.TEMPLATE_UNIQUE AND SIGN_DOCNUMET.DOC_UNIQUE IN(SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1 WHERE   (DOC_DOCUMENTID LIKE '%@%') GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45)) AND MARK_NAME='设计' UNION (SELECT SIGN_DOCNUMET.DOC_UNIQUE,SIGN_DOCNUMET.DOC_NAME, SUBSTRING(SIGN_DOCNUMET.DOC_DOCUMENTID, 10, 40) AS DOC_REAL_NAME, SIGN_DOCNUMET.DOC_TYPE, SIGN_DOCNUMET.DOC_STATUS, SIGN_DOCNUMET.CREATE_TIME, SIGN_DOCNUMET.ErrorMsg,CASE WHEN SIGN_DOCNUMET.DOC_STATUS = '2' THEN '成功' WHEN SIGN_DOCNUMET.DOC_STATUS = '3' THEN '失败' WHEN SIGN_DOCNUMET.DOC_STATUS = '1' THEN '代签' WHEN SIGN_DOCNUMET.DOC_STATUS = '6' THEN '正在盖章' END AS STATUS,SIGN_TEMPLATE_WPS.SIGN_NAME AS [USRNAME],SIGN_TEMPLATE_WPS.SIGN_KEY AS [USRCODE] FROM SIGN_DOCNUMET,REL_DOC_STEMP,SIGN_TEMPLATE_WPS WHERE SIGN_DOCNUMET.DOC_UNIQUE = REL_DOC_STEMP.DOC_UNIQUE AND REL_DOC_STEMP.TEMPLATE_UNIQUE = SIGN_TEMPLATE_WPS.TEMPLATE_UNIQUE AND SIGN_DOCNUMET.DOC_UNIQUE IN (SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1 WHERE   (DOC_DOCUMENTID LIKE '%@%') GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))AND MARK_NAME='设计'))

INSERT INTO [dbo].[SIGN_DOCNUMET_INSIG_INFO]([DOC_UNIQUE],[DOC_NAME],[DOC_REAL_NAME],[DOC_TYPE],[DOC_STATUS],[CREATE_TIME],[ErrorMsg],[STATUS]) (SELECT   DOC_UNIQUE, DOC_NAME, SUBSTRING(DOC_DOCUMENTID, 10, 45) AS DOC_REAL_NAME, DOC_TYPE, DOC_STATUS, CREATE_TIME, ErrorMsg, CASE WHEN DOC_STATUS = '2' THEN '成功' WHEN DOC_STATUS = '3' THEN '失败' WHEN DOC_STATUS = '1' THEN '代签' WHEN DOC_STATUS = '6' THEN '正在盖章' END AS STATUS FROM  SIGN_DOCNUMET WHERE  (DOC_UNIQUE IN (SELECT   MAX(DOC_UNIQUE) AS Expr1 FROM  SIGN_DOCNUMET AS SIGN_DOCNUMET_1 WHERE   (DOC_DOCUMENTID LIKE '%@%') GROUP BY SUBSTRING(DOC_DOCUMENTID, 10, 45))) and DOC_UNIQUE not in (select DOC_UNIQUE from SIGN_DOCNUMET_INSIG_INFO))

SELECT * FROM dbo.SIGN_DOCNUMET_INSIG_INFO ORDER BY DOC_UNIQUE DESC



/****** Script for SelectTopNRows command from SSMS  ******/
  SELECT [DOC_UNIQUE]
      ,[DOC_DOCUMENTID] as [DOC_NAME]   
      ,SUBSTRING(DOC_DOCUMENTID,10,40) as [DOC_REAL_NAME]
	  ,[DOC_TYPE]
      ,[DOC_STATUS]
      ,[CREATE_TIME]
      ,[ErrorMsg]      
	  ,CASE WHEN SIGN_DOCNUMET.DOC_STATUS = '2' THEN '成功' WHEN SIGN_DOCNUMET.DOC_STATUS = '3' THEN '失败' WHEN SIGN_DOCNUMET.DOC_STATUS = '1' THEN '代签' WHEN SIGN_DOCNUMET.DOC_STATUS = '6' THEN '正在盖章' END AS [STATUS]
	  ,'请选择' as Remark
	  FROM dbo.SIGN_DOCNUMET WHERE DOC_UNIQUE IN(
  SELECT MAX(DOC_UNIQUE) FROM dbo.SIGN_DOCNUMET
  WHERE DOC_DOCUMENTID LIKE '%@%'
  AND CREATE_TIME>='2016.09.01'
  GROUP BY SUBSTRING(DOC_DOCUMENTID,10,40)) AND SUBSTRING(DOC_DOCUMENTID,10,40)  NOT IN (SELECT [DOC_REAL_NAME] FROM SIGN_DOCNUMET_INSIG_INFO)



--查询文件列表（最新、不重复）
  select * from SIGN_DOCNUMET
  WHERE DOC_UNIQUE in(
  SELECT MAX(DOC_UNIQUE) FROM dbo.SIGN_DOCNUMET
  WHERE DOC_DOCUMENTID LIKE '%@%' and CREATE_TIME>='2016.09.01'
  GROUP BY SUBSTRING(DOC_DOCUMENTID,10,40))
  order by DOC_UNIQUE desc


--删除视图
go

drop view view_signinfo

go


--创建视图
  go
  create view view_signinfo as
  (select [DOC_UNIQUE]
      ,[DOC_DOCUMENTID] as [DOC_NAME]   
      ,SUBSTRING(DOC_DOCUMENTID,10,40) as [DOC_REAL_NAME]
	  ,[DOC_TYPE]
	  ,[DOC_STATUS]
      ,[CREATE_TIME]
      ,[ErrorMsg]      
	  ,CASE WHEN SIGN_DOCNUMET.DOC_STATUS = '2' THEN '成功' WHEN SIGN_DOCNUMET.DOC_STATUS = '3' THEN '失败' WHEN SIGN_DOCNUMET.DOC_STATUS = '1' THEN '代签' WHEN SIGN_DOCNUMET.DOC_STATUS = '6' THEN '正在盖章' END AS [STATUS]
	  ,'请选择' as Remark from SIGN_DOCNUMET
  WHERE DOC_UNIQUE in(
  SELECT MAX(DOC_UNIQUE) FROM dbo.SIGN_DOCNUMET
  WHERE DOC_DOCUMENTID LIKE '%@%' and CREATE_TIME>='2016.09.01'
  GROUP BY SUBSTRING(DOC_DOCUMENTID,10,40)))
  go


--查询视图内容  
select * from view_signinfo


--批量更新表[SIGN_DOCNUMET_INSIG_INFO_Bak] 
update p set p.DOC_UNIQUE = u.DOC_UNIQUE,p.DOC_NAME = u.DOC_NAME,p.DOC_STATUS = u.DOC_STATUS, p.CREATE_TIME = u.CREATE_TIME,p.ErrorMsg = u.ErrorMsg,p.STATUS = u.STATUS
from [SIGN_DOCNUMET_INSIG_INFO_Bak] p, view_signinfo u
where p.[DOC_REAL_NAME] = u.[DOC_REAL_NAME] 

